[package]
name = "arel"
version = "0.0.0"
edition = "2021"
description = "simulate rails arel"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
Inflector = "^0.11.4"
serde_json = "1.0.64"
regex = "1.5.4"