name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --features mysql --verbose
    - name: Run tests with mysql features
      run: cargo test -p arel --features mysql --verbose
    - name: Run sqlx tests with sqlite features
      run: cargo test sqlx -p arel --features sqlite --verbose
