name: Rust

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --features mysql --verbose
    - name: Run tests with mysql features
      run: cargo test -p arel --features mysql --verbose
    - name: Run tests with sqlite features
      run: cargo test -p arel --features sqlite --verbose -- --skip sqlite_sqlx
    - name: Run sqlx default tests with sqlite features
      run: cargo test sqlite_sqlx_default -p arel --features sqlite --verbose
    - name: Run sqlx default tests with sqlite features
      run: cargo test sqlite_sqlx_association -p arel --features sqlite --verbose
